### ISSUE TITLE
Timestamp Discrepancy Across Devices for the Same Node

### ISSUE THREAD

**Issue by Nackoo2000** [breez/misty-breez#266]
![image](https://github.com/user-attachments/assets/f969d682-1a9a-480c-ab00-664bf44d9b25)
![image](https://github.com/user-attachments/assets/8a21ed7d-f368-41a3-beef-6a4252545229)

**Comment by roeierez** [comment]
@hydra-yse I have checked the db file of the wallet that shows the wrong time and the claim tx in the tx_data table is unconfirmed and the timestamp is NULL there.
I am guessing the payment is shown as completed because we synced in the preimage but we need to check why this transaction is not updated to be confirmed eventually. 
@Nackoo2000 when you open the wallet with the 12:37 timestamp does it still show this wrong timestamp or it is updated to the correct one?
